# Generated by Django 4.0.2 on 2022-02-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=20)),
                ('data', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
